// Auto-generated by sync script
import { lazy } from 'react';

export const menuItems = [
    { id: 'disclaimer', label: '说明文档', component: lazy(() => import('./components/Disclaimer')) },
    { id: 'LTV 价值评分系统', label: 'LTV 价值评分系统', component: lazy(() => import('./components/synced/LTVScoringDemo')) },
    { id: '主管监控看板', label: '主管监控看板', component: lazy(() => import('./components/synced/TeamDashboard')) },
    { id: '多渠道加微三连击', label: '多渠道加微三连击', component: lazy(() => import('./components/synced/ThreeStrikeStrategy')) },
    { id: '微信侧边栏', label: '微信侧边栏', component: lazy(() => import('./components/synced/TripleHitDemo')) },
    { id: '意图和情绪分析', label: '意图和情绪分析', component: lazy(() => import('./components/synced/IntentAnalysisDemo')) },
    { id: '撞单仲裁与合并', label: '撞单仲裁与合并', component: lazy(() => import('./components/synced/App')) },
    { id: '沉默线索再激活', label: '沉默线索再激活', component: lazy(() => import('./components/synced/SilentReactivationDemo')) },
    { id: '渠道 ROI 实时罗盘', label: '渠道 ROI 实时罗盘', component: lazy(() => import('./components/synced/ChannelROIDashboard')) },
    { id: '画像质量治理驾驶舱', label: '画像质量治理驾驶舱', component: lazy(() => import('./components/synced/CompletenessDashboard')) },
    { id: '运维面板', label: '运维面板', component: lazy(() => import('./components/synced/ConfigPanel')) },
    { id: '销售作战地图', label: '销售作战地图', component: lazy(() => import('./components/synced/SmartClientList')) },
    { id: '阶段策略路由', label: '阶段策略路由', component: lazy(() => import('./components/synced/StageRoutingDemo')) }
];
