import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const demoSiteDir = path.resolve(root, 'docs/Personal/子君AI销售系统/demo-site');
const examplesDir = path.resolve(root, 'docs/Personal/子君AI销售系统/示例');
const componentsSrcDir = path.resolve(root, 'src/components');
const componentsDestDir = path.resolve(demoSiteDir, 'src/components/synced');

// 确保目标目录存在
if (!fs.existsSync(componentsDestDir)) {
    fs.mkdirSync(componentsDestDir, { recursive: true });
}

const files = fs.readdirSync(examplesDir).filter(f => f.endsWith('.mdx'));
const menuConfig = [];

files.forEach(file => {
    const content = fs.readFileSync(path.join(examplesDir, file), 'utf-8');
    const name = file.replace('.mdx', '');
    
    // 简单的正则匹配组件导入: import X from '@site/src/components/Y';
    const importMatch = content.match(/import\s+(\w+)\s+from\s+'@site\/src\/components\/([^']+)';/);
    
    if (importMatch) {
        const componentName = importMatch[1];
        const componentPath = importMatch[2];
        const sourceFile = path.resolve(componentsSrcDir, componentPath.endsWith('.tsx') ? componentPath : `${componentPath}.tsx`);
        const destFile = path.resolve(componentsDestDir, `${componentName}.tsx`);
        
        if (fs.existsSync(sourceFile)) {
            fs.copyFileSync(sourceFile, destFile);
            console.log(`Synced component: ${componentName}`);
            
            menuConfig.push({
                label: name,
                component: componentName
            });
        }
    }
});

// 生成配置信息
const configContent = `// Auto-generated by sync script
import { lazy } from 'react';

export const menuItems = [
    { id: 'disclaimer', label: '说明文档', component: lazy(() => import('./components/Disclaimer')) },
    ${menuConfig.map(item => `{ id: '${item.label}', label: '${item.label}', component: lazy(() => import('./components/synced/${item.component}')) }`).join(',\n    ')}
];
`;

fs.writeFileSync(path.resolve(demoSiteDir, 'src/config.ts'), configContent);
console.log('Sync complete!');
